# Generated by Django 4.2.27 on 2026-04-12 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagesection',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ru', 'Русский'), ('hy', 'Հայերեն')], default='en', max_length=5),
        ),
    ]
