# Generated by Django 4.2.27 on 2026-04-12 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_pagesection_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagesection',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ru', 'Русский'), ('am', 'Հայերեն')], default='en', max_length=5),
        ),
    ]
