# Generated by Django 6.0.1 on 2026-04-13 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_pagesection_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='show_in_nav',
            field=models.BooleanField(default=True),
        ),
    ]
