# Generated by Django 6.0.1 on 2026-04-13 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_add_show_in_nav_to_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagesection',
            name='section_type',
            field=models.CharField(choices=[('hero', 'Hero'), ('features_carousel', 'Features Carousel'), ('about_teaser', 'About Teaser'), ('services', 'Services'), ('why_choose_us', 'Why Choose Us'), ('team', 'Team'), ('steps', 'Steps'), ('testimonials', 'Testimonials'), ('blog', 'Blog'), ('about_hero_text', 'About Hero Text'), ('about_values', 'About Values'), ('about_tech', 'About Tech'), ('about_video', 'About Video'), ('about_conference', 'About Conference'), ('text_block', 'Text Block'), ('card_grid', 'Card Grid'), ('card_carousel', 'Card Carousel'), ('video_block', 'Video Block')], max_length=30),
        ),
    ]
