# Generated by Django 6.0.1 on 2026-04-13 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_add_video_block_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionitem',
            name='link_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
